#!/bin/bash

SUBVOLS="
	.snapshots
	boot/grub2/i386-pc
	boot/grub2/x86_64-efi
	boot/writable
	home
	opt
	root
	srv
	usr/local
	var
"

PACKAGES="
	patterns-base-bootloader
	patterns-containers-container_runtime
	patterns-microos-base
	patterns-microos-base-zypper
	patterns-microos-defaults
	patterns-microos-desktop-gnome
	patterns-microos-hardware
	patterns-microos-selinux
	accountsservice-lang
	irqbalance
	iso-codes-lang
	kernel-default
	numactl
	nvme-cli
	os-prober
	sg3_utils
	grub2-i386-pc-extras
	grub2-x86_64-efi-extras
"

# Missing packages:
#	firmwares (maybe using -all?)
# 	ucode-amd/ucode-intel
# 	xf86-video-r128/intel, VM/Guest-tools
# This stuff is decided during yast installation.

TMPMNT=$(mktemp -d)
RUNDATE=$(date '+%Y-%m-%d %T')
GREEN='\033[1m\033[32m'
YELLOW='\033[1m\033[33m'
RED='\033[1m\033[31m'
CLEAR='\033[0m'

print_yellow() {
	printf "${YELLOW}"
	printf "%s\n" "$@"
	printf "${CLEAR}"
}

print_green() {
	printf "${GREEN}"
	printf "%s\n" "$@"
	printf "${CLEAR}"
}

print_red() {
	printf "${RED}"
	printf "%s\n" "$@"
	printf "${CLEAR}"
}

[ -r /etc/os-release ] && . /etc/os-release
if [ "${ID%%[ ]*}" != "opensuse-microos" ]; then
	print_red "This script is only for openSUSE MicroOS"
	exit
fi

if [ "$EUID" -ne 0 ]; then
	sudo "$0" "$@"
	exit
fi

print_red "This is a prototype script that may do terrible things to your system, you have been warned"
read -p "Do you want to continue? (yes/no) " yn
case $yn in
	yes) print_green "OK" ;;
	no)
		echo exiting...
		exit
		;;
	*)
		echo invalid response
		exit 1
		;;
esac

print_yellow "DEMO: Create New MicroOS Desktop (GNOME) Installation in fresh subvolume. Fool tukit/snapper into thinking its a valid snapshot"

# Create snapshot
LATESTSNAP=$(tukit -q snapshots | tail -n1)
WORKSNAP=$((LATESTSNAP + 1))
mkdir /.snapshots/$WORKSNAP
btrfs subvolume create /.snapshots/$WORKSNAP/snapshot

mkdir -p /.snapshots/$WORKSNAP/snapshot/boot/writable
mkdir -p /.snapshots/$WORKSNAP/snapshot/.snapshots

# Create dummy snapper XML
cat << EOF > /.snapshots/$WORKSNAP/info.xml
<?xml version="1.0"?>
<snapshot>
  <type>single</type>
  <num>$WORKSNAP</num>
  <date>$RUNDATE</date>
  <description>mod-check Powerwash</description>
  <userdata>
    <key>transactional-update-in-progress</key>
    <value>yes</value>
  </userdata>
</snapshot>
EOF

systemctl restart snapperd

print_red "DEBUG: Install MicroOS GNOME to $WORKSNAP"
zypper -R /.snapshots/$WORKSNAP/snapshot --gpg-auto-import-keys ar -f \
	http://mirrorcache-eu.opensuse.org/tumbleweed/repo/oss/ repo-non-oss

ZYPP_SINGLE_RPMTRANS=1 zypper -R /.snapshots/$WORKSNAP/snapshot \
	--gpg-auto-import-keys in $PACKAGES

# Grab current fstab, except for last overlay mount
fstab_content="$(cat /etc/fstab | head -n -1)"

# backup original fstab
cp /.snapshots/$WORKSNAP/snapshot/etc/fstab /.snapshots/$WORKSNAP/snapshot/etc/fstab.bak

# Create new fstab with current layout, and new overlay mount
echo "$fstab_content" > /.snapshots/$WORKSNAP/snapshot/etc/fstab
cat /.snapshots/$WORKSNAP/snapshot/etc/fstab.bak >> /.snapshots/$WORKSNAP/snapshot/etc/fstab

systemctl restart snapperd

cp -r /boot/grub2/* /.snapshots/6/snapshot/boot/grub2/

# Now we set up the boot correctly, tukit call enables us to launch commands in
# an existing snapshot
/sbin/tukit call $WORKSNAP dracut --force --regenerate-all
/sbin/tukit call $WORKSNAP /usr/sbin/grub2-mkconfig -o /boot/grub2/grub.cfg
/sbin/tukit call $WORKSNAP chcon --reference /boot/grub2/grub.cfg  /.snapshots/$WORKSNAP/snapshot/boot/grub2/grub.cfg
/sbin/tukit call $WORKSNAP /sbin/pbl --install

# Missing piece, this will make the snapshot actually bootable
/usr/lib/snapper/plugins/grub --enable $WORKSNAP

/sbin/tukit close $WORKSNAP


#TODO - cleanup in case of abort/error
#TODO - edit etc/fstab to look like a regular t-u snapshots one
#TODO - populate etc/fstab with etc/fstab from the existing host
#TODO - delete var/lib/overlay/1
